-- ORG table
CREATE TABLE IF NOT EXISTS ORG (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ENABLED BOOLEAN NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

-- TEAM table
CREATE TABLE IF NOT EXISTS TEAM (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ORG_ID INT NOT NULL,
    FOREIGN KEY (ORG_ID) REFERENCES ORG(ID) ON DELETE CASCADE
);

-- APP_USER table
CREATE TABLE IF NOT EXISTS APP_USER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    API_KEY VARCHAR(255),
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    ORG_ID INT NOT NULL,
    TEAM_ID INT NOT NULL,
    USER_TYPE ENUM('SITE_ADMIN', 'SITE_SUPPORT', 'USER') NOT NULL,
    FOREIGN KEY (ORG_ID) REFERENCES ORG(ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID) ON DELETE CASCADE
);

-- ORG_ADMIN table
CREATE TABLE IF NOT EXISTS ORG_ADMIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    ORG_ID INT NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (ORG_ID) REFERENCES ORG(ID) ON DELETE CASCADE
);

-- TEAM_ADMIN table
CREATE TABLE IF NOT EXISTS TEAM_ADMIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TEAM_ID INT NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID) ON DELETE CASCADE
);

-- SITE_ADMIN table
CREATE TABLE IF NOT EXISTS SITE_ADMIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ACTOR_ID INT,  -- Nullable for anonymous or system actions
    ACTION VARCHAR(64) NOT NULL, -- 'CREATE_USER', 'UPDATE_TEAM', etc.
    TARGET_TABLE VARCHAR(64) NOT NULL,
    TARGET_ID INT,
    PAYLOAD JSON,  -- Full delta or snapshot
    CONTEXT JSON,  -- Optional metadata: IP, user-agent, etc.
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACTOR_ID) REFERENCES APP_USER(ID) ON DELETE SET NULL
);
