-- ORG table
CREATE TABLE IF NOT EXISTS ORG (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ENABLED BOOLEAN NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

-- TEAM table
CREATE TABLE IF NOT EXISTS TEAM (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ORG_ID INT NOT NULL,
    FOREIGN KEY (ORG_ID) REFERENCES ORG(ID) ON DELETE CASCADE
);

-- USER table
CREATE TABLE IF NOT EXISTS USER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    API_KEY VARCHAR(255),
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    ORG_ID INT NOT NULL,
    TEAM_ID INT NOT NULL,
    FOREIGN KEY (ORG_ID) REFERENCES ORG(ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID) ON DELETE CASCADE
);

-- ORG_ADMIN table
CREATE TABLE IF NOT EXISTS ORG_ADMIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    ORG_ID INT NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    CREATED DATE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (ORG_ID) REFERENCES ORG(ID) ON DELETE CASCADE
);

-- TEAM_ADMIN table
CREATE TABLE IF NOT EXISTS TEAM_ADMIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TEAM_ID INT NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    CREATED DATE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID) ON DELETE CASCADE
);
